import assert from 'node:assert/strict'
import { test } from 'node:test'
import { createRuntimeCapabilityClient } from '../apps/desktop-pet/src/desktop/runtime-client.mjs'

function json(value, status = 200, headers = {}) {
  return new Response(JSON.stringify(value), { status, headers: { 'content-type': 'application/json; charset=utf-8', ...headers } })
}

test('desktop bridge exposes a safe worksite projection and bounded controls', async () => {
  const calls = []
  const fetchImpl = async (url, options = {}) => {
    const parsed = new URL(url)
    calls.push({ path: parsed.pathname, query: parsed.search, method: options.method || 'GET', body: options.body ? JSON.parse(options.body) : undefined })
    if (parsed.pathname === '/api/product/workspace') return json({ revision: 7, host: { schemaVersion: 1 } })
    if (parsed.pathname === '/api/product/host/sessions') return json({ items: [{ host: 'codex', session_id: 'abc', status: 'attached', project_ref: 'C:\\private\\project', updated_at: '2026-09-17T00:00:00Z' }] })
    if (parsed.pathname === '/api/product/host/turns') return json({ items: [{ turn_id: 'turn-1', prompt: 'private prompt' }] })
    if (parsed.pathname === '/api/product/host/findings') return json({ items: [{ finding_kind: 'captured', status: 'open', observation: '持续记录一个工作信号' }] })
    if (parsed.pathname === '/api/product/host/sensemaking/jobs') return json({ items: [{ status: 'queued', execution_mode: 'shadow' }] })
    if (parsed.pathname === '/api/product/host/routing/proposals') return json({ items: [{ proposal_id: 'proposal-1', status: 'proposed', target_kind: 'workflow', scope: 'project', rationale: '可复用的工作信号', revision: 3 }] })
    if (parsed.pathname === '/api/product/host/activation/history') return json({ items: [{ receipt_id: 'receipt-1', status: 'offered', item_count: 1 }] })
    if (parsed.pathname === '/api/agent/sensemaking/health') return json({ status: 'running', mode: 'fixture-dev', queue_depth: 2, failed_count: 0 })
    if (parsed.pathname === '/api/product/host/repository/recovery/status') return json({ items: [{ state: 'recovery_required', journal_id: 'journal-1', expected_branch: 'trace/work' }] })
    if (parsed.pathname === '/api/product/host/publication-policies') return json({ items: [{ status: 'active', scope: 'project', policy_id: 'policy-1', revision: 2, target_root: 'C:\\private\\project' }] })
    if (parsed.pathname === '/api/product/host/capability/orchestrations') return json({ items: [{ status: 'candidate', orchestration_id: 'orch-1', revision: 4, candidate_dir: 'C:\\private\\candidate', manifest_sha256: 'a'.repeat(64), candidate: { producer_status: 'staged' } }] })
    if (parsed.pathname === '/api/product/host/capability/trials') return json({ items: [{ status: 'queued', trial_id: 'trial-1', orchestration_id: 'orch-1', revision: 0, outcome: null }] })
    if (parsed.pathname === '/api/product/host/repository/preflight') return json({ protocolVersion: 1, preflight_id: 'backend-preflight-1', state_hash: 'state-hash-1', action: 'create-branch' })
    if (parsed.pathname === '/api/product/host/repository/apply') return json({ protocolVersion: 1, status: 'applied' })
    if (parsed.pathname === '/api/product/host/publication-policy/preview') return json({ protocolVersion: 1, policy_id: 'policy-preview-1', scope: 'project', target_root: 'C:\\private\\project', allowed_capability_kinds: ['skill'], validation_requirements: { schema: 'passed' } })
    if (parsed.pathname === '/api/product/host/publication-policy/adopt') return json({ protocolVersion: 1, status: 'active' })
    if (parsed.pathname === '/api/product/host/capability/trial/create') return json({ protocolVersion: 1, status: 'trial_queued' })
    if (parsed.pathname === '/api/product/host/session/attach') return json({ status: 'attached' })
    if (parsed.pathname === '/api/product/commands') return json({ protocolVersion: 1, revision: 8, host: { schemaVersion: 1 } })
    if (parsed.pathname === '/api/agent/runs/run-1/cancel') return json({ status: 'cancelled' })
    if (parsed.pathname === '/api/agent/runs/run-1/adoption') return json({ action: calls.at(-1)?.body?.action, run: { status: 'succeeded' } })
    if (parsed.pathname === '/api/zhihu/user/read') return json({ resource: calls.at(-1)?.body?.kind, items: [] })
    throw new Error(`unexpected request: ${parsed.pathname}`)
  }
  const client = createRuntimeCapabilityClient({ origin: 'http://127.0.0.1:42731', cloudOrigin: 'https://trace.neutrom.store', projectDir: process.cwd(), fetchImpl, cloudFetchImpl: fetchImpl })
  const panel = await client.request({ operation: 'host.panel.read' })
  assert.equal(panel.connected, true)
  assert.equal(panel.sessions[0].project, '已绑定当前项目')
  assert.equal(panel.findings[0].summary, '持续记录一个工作信号')
  assert.equal(panel.recovery[0].expectedBranch, '已记录目标分支')
  assert.equal(panel.policies[0].id, 'policy-1')
  await client.request({ operation: 'host.panel.action', action: 'session.attach' })
  await assert.rejects(() => client.request({ operation: 'host.panel.action', action: 'repository.apply', preflightId: 'missing', confirmation: 'user-confirmed' }), /预检|回执/)
  const preflight = await client.request({ operation: 'host.panel.action', action: 'repository.preflight', proposalId: 'proposal-1' })
  assert.equal(preflight.canApply, true)
  await assert.rejects(() => client.request({ operation: 'host.panel.action', action: 'repository.apply', preflightId: preflight.preflightId }), /确认/)
  await client.request({ operation: 'host.panel.action', action: 'repository.apply', preflightId: preflight.preflightId, confirmation: 'user-confirmed' })
  const policyPreview = await client.request({ operation: 'host.panel.action', action: 'publication.policy.preview', scope: 'project' })
  await assert.rejects(() => client.request({ operation: 'host.panel.action', action: 'publication.policy.adopt', previewId: policyPreview.previewId }), /确认/)
  await client.request({ operation: 'host.panel.action', action: 'publication.policy.adopt', previewId: policyPreview.previewId, confirmation: 'user-confirmed' })
  await client.request({ operation: 'host.panel.action', action: 'capability.trial.create', orchestrationId: 'orch-1', expectedRevision: 4, scenario: '验证项目边界' })
  await client.request({ operation: 'product.command', protocolVersion: 1, commandId: 'desktop-command-1', expectedRevision: 7, operations: [{ type: 'capture.draft', text: '保留这句' }] })
  await client.request({ operation: 'agent.run.cancel', runId: 'run-1' })
  await client.request({ operation: 'agent.run.adoption', runId: 'run-1', action: 'dismiss' })
  const user = await client.request({ operation: 'zhihu.user.read', kind: 'favorite_items', favorite_id: 'favorite-1', limit: 10, offset: '0' })
  assert.equal(user.resource, 'favorite_items')
  assert.equal(calls.find((item) => item.path === '/api/product/host/session/attach').body.projectRef, process.cwd())
  assert.equal(calls.find((item) => item.path === '/api/zhihu/user/read').body.limit, 10)
  const applyCall = calls.find((item) => item.path === '/api/product/host/repository/apply')
  assert.equal(applyCall.body.preflightId, 'backend-preflight-1')
  assert.equal(applyCall.body.expectedStateHash, 'state-hash-1')
  assert.equal(calls.find((item) => item.path === '/api/product/host/publication-policy/adopt').body.approval, 'adopt:policy-preview-1')
  await assert.rejects(() => client.request({ operation: 'zhihu.user.read', kind: 'favorites', limit: 11, offset: '0' }), /bounded|最多|Invalid/)
})
