const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const port=Number(process.env.TRACE_TEST_PORT||4182);
if(!Number.isInteger(port)||port<1024||port>65535) throw new Error('TRACE_TEST_PORT must be an integer from 1024 to 65535');
const base='http://127.0.0.1:'+port;
const out=path.resolve(__dirname,'../.test-results/e2e/run-'+Date.now());fs.mkdirSync(out,{recursive:true});const checks=[],errors=[];
const text='按钮越少，第一次填写就越容易吗？🧪 我想先比较必要步骤。';
const U1='先保留必要条件，再减少操作步骤。这里只讨论首次填写。', U2='先保留可见的必要条件，再减少操作步骤；步骤少不等于首次填写更容易。';
(async()=>{const server=spawn(process.execPath,['server.mjs'],{cwd:path.resolve(__dirname,'../apps/web'),env:{...process.env,TRACE_DESKTOP_PORT:String(port),TRACE_WEB_STATE_FILE:path.join(out,'web.sqlite')},windowsHide:true,stdio:['ignore','pipe','pipe']});let serverLog='',serverError;server.on('error',error=>{serverError=error});server.stdout.on('data',c=>serverLog+=c);server.stderr.on('data',c=>serverLog+=c);
let browser,p;try{for(let i=0;i<100;i++){
if(serverError) throw serverError;
if(server.exitCode!==null) throw new Error('Isolated test server exited: '+serverLog);
if(serverLog.includes('Trace Web: '+base+'/')) break;
await new Promise(r=>setTimeout(r,100));
}
if(!serverLog.includes('Trace Web: '+base+'/')) throw new Error('Isolated test server did not start: '+serverLog);
browser=await chromium.launch({executablePath:process.env.TRACE_CHROMIUM_EXECUTABLE||undefined,headless:true});p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.dismiss());
const state=async()=>(await(await fetch(base+'/api/web/workspace')).json());
const settled=async()=>{await p.waitForTimeout(500);await p.locator('.web-status[data-state=saved]').waitFor({timeout:8000});await p.waitForFunction(()=>!document.querySelector('#app').inert)};
const check=(name,value=true)=>{assert.ok(value,name);checks.push({name,passed:true});console.log('PASS '+name)};
const shot=async name=>{await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(out,name+'.png')})};
await p.goto(base+'/app');await p.locator('#capture-input').waitFor();check('real empty workspace',(await state()).host===null);await shot('01-home');
await p.locator('#capture-input').fill(text);await p.locator('#capture-form [type=submit]').click();await p.locator('[data-selection=originalText]').waitFor();await settled();const M=new URL(p.url()).searchParams.get('matter');let data=await state();check('capture one canonical matter',data.host.chain.matters.length===1&&data.host.chain.matters[0].id===M);check('original literal, no understanding',data.host.chain.matters[0].originalText===text&&data.host.chain.matters[0].understanding==='');
await p.locator('[data-selection=originalText]').evaluate(el=>{const r=document.createRange();r.setStart(el.firstChild,0);r.setEnd(el.firstChild,18);getSelection().removeAllRanges();getSelection().addRange(r);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));});await p.locator('[data-action=comparison]').click();await p.locator('.compare-root').waitFor();await settled();check('compare accepts original basis',(await state()).host.chain.matters[0].understanding==='');await p.locator('[data-action=import]').first().click();await p.locator('#compare-material-title').fill('验收材料 A');await p.locator('#compare-material-excerpt').fill('步骤少了，但两个必填条件被藏起来，首次填写者需要返回补全。');await p.locator('[data-form=import] [type=submit]').click();await p.locator('[data-action=link]').waitFor();await settled();await shot('02-comparison');await p.locator('[data-action=link]').click();await p.locator('#compare-relation').selectOption({label:'限制'});await p.locator('[data-action=confirm-link]').click();await settled();data=await state();check('LINK persists only relation',data.host.chain.matters[0].links.length===1&&data.host.chain.matters[0].understanding===''&&data.host.chain.matters[0].understandingVersion===0);await p.locator('.compare-top-return').click();await p.locator('[data-selection=originalText]').waitFor();check('return same matter and anchor',new URL(p.url()).searchParams.get('matter')===M&&await p.evaluate(()=>getSelection().toString())===text.slice(0,18));await shot('03-linked-return');
await p.locator('[data-action=understanding]').first().click();await p.locator('[data-field=understanding]').fill(U1);await p.locator('[data-action=save-understanding]').click();await settled();data=await state();check('explicit understanding save same matter v1',data.host.chain.matters[0].understanding===U1&&data.host.chain.matters[0].understandingVersion===1);await p.reload();await p.locator('[data-field=understanding]').waitFor();check('refresh preserves understanding',await p.locator('[data-field=understanding]').inputValue()===U1);await shot('04-understanding');
await p.locator('[data-action=handoff]').click();await p.locator('[data-field=agent]').fill('本地编辑器');await p.locator('[data-field=project]').fill('首次填写体验');await p.locator('[data-field=task]').fill('验证必要条件是否清楚');await p.locator('[data-action=confirm-handoff]').click();await p.locator('.worksite-viewport').waitFor();await settled();data=await state();const W=Object.keys(data.host.worksite.works)[0];check('work exact intake v1 not sent',data.host.worksite.sessions[W].intake[0].sourceText===U1&&data.host.worksite.sessions[W].intake[0].sourceVersion===1&&data.host.worksite.works[W].connected===false);await shot('05-worksite');
await p.locator('[data-action=results]').filter({visible:true}).first().click();await p.locator('[data-field=result-fact]').fill('验收数据：移除说明后，第一次填写漏掉了一个必要条件。');await p.locator('[data-field=result-interpretation]').fill('可能是条件提示被一并移除了。');await p.locator('[data-field=result-unknown]').fill('还未验证其他表单。');await p.locator('[data-action=keep-result]').click();await settled();data=await state();check('result-only preserved understanding',data.host.chain.matters[0].understanding===U1&&data.host.worksite.sessions[W].results.length===1);await p.locator('[data-field=result-proposed]').fill(U2);await p.locator('[data-action=review]').click();await p.locator('[data-action=cancel-review]').first().click();await settled();check('cancel review no revision',(await state()).host.chain.matters[0].understandingVersion===1);await p.locator('[data-action=review]').click();await p.locator('[data-action=confirm-review]').click();await settled();data=await state();check('result explicit revision v2 same matter',data.host.chain.matters[0].understanding===U2&&data.host.chain.matters[0].understandingVersion===2);check('old intake snapshot stays v1',data.host.worksite.sessions[W].intake[0].sourceVersion===1);await shot('06-result');
await p.locator('[data-action=result-matter]').click();await p.locator('[data-field=understanding]').waitFor();check('result returns original current understanding',await p.locator('[data-field=understanding]').inputValue()===U2);await p.locator('.web-context-menu').getByRole('button',{name:'搜索',exact:true}).click();await p.locator('input[type=search]').fill('必要条件');const searchURL=p.url();await p.locator('[data-kind=result]').click();await p.locator('[data-open]').first().click();await p.locator('.web-dialog').waitFor();await p.locator('.web-dialog button[aria-label=关闭]').click();await p.locator('.web-continuity').getByRole('button',{name:'← 返回搜索结果'}).click();await p.locator('input[type=search]').waitFor();check('query/type restored on internal return',await p.locator('input[type=search]').inputValue()==='必要条件'&&new URL(p.url()).searchParams.get('kind')==='result');await p.reload();await p.locator('input[type=search]').waitFor();check('search deep link refresh',await p.locator('input[type=search]').inputValue()==='必要条件');await shot('07-search');
await p.locator('.web-profile').click();await p.locator('.web-dialog input[name=name]').fill('验证者');await p.locator('.web-dialog [type=submit]').click();await settled();check('settings saved',(await state()).host.preferences.displayName==='验证者');check('settings leaves search in place',await p.locator('input[type=search]').inputValue()==='必要条件');const exported=await(await fetch(base+'/api/web/export')).json();check('export has real data',JSON.stringify(exported).includes(M)&&JSON.stringify(exported).includes(U2));
// Latest understanding is a new intake, not a replacement of the old work snapshot.
await p.goto(base+'/?view=worksite&work='+encodeURIComponent(W)+'&matter='+encodeURIComponent(M)+'&screen=results');await p.locator('[data-action=retry]').waitFor();await p.locator('[data-action=retry]').click();await p.locator('[data-field=task]').waitFor();await settled();await p.locator('[data-action=confirm-handoff]').click();await p.locator('.worksite-viewport').waitFor();await settled();data=await state();const W2=Object.keys(data.host.worksite.works).find(id=>id!==W);check('retry creates new work from v2',data.host.worksite.sessions[W2].intake[0].sourceVersion===2&&data.host.worksite.sessions[W].intake[0].sourceVersion===1);
await p.goto(base+'/?view=chain&matter='+encodeURIComponent(M)+'&screen=resume');await p.locator('[data-action=fresh]').click();await settled();await p.locator('[data-field=composer]').fill('这次只关心熟练填写者。');await p.locator('[data-form=send] [type=submit]').click();await settled();await p.locator('[data-action=comparison]').click();await p.locator('.compare-root').waitFor();await settled();data=await state();const sid=new URL(p.url()).searchParams.get('session');check('fresh comparison uses only new discussion',data.host.comparisons[sid].anchor.text==='这次只关心熟练填写者。');await p.locator('.compare-top-return').click();await p.locator('.chain-root').waitFor();check('fresh survives return',(await state()).host.chain.sessions[M].contextMode==='fresh');
// Failed autosave A must not mark newer B saved when retrying A.
await p.goto(base+'/?view=home');await p.locator('#capture-input').waitFor();let failOnce=true;await p.route('**/api/web/workspace',async r=>{if(r.request().method()==='PUT'&&failOnce){failOnce=false;await r.abort('failed');}else await r.continue();});await p.locator('#capture-input').fill('未保存的草稿 A');await p.locator('.web-status[data-state=error]').waitFor();await p.locator('#capture-input').fill('后来继续写的草稿 B');await p.locator('[data-retry]').click();await settled();await p.reload();await p.locator('#capture-input').waitFor();check('failed A retry also persists newer B',await p.locator('#capture-input').inputValue()==='后来继续写的草稿 B');await p.unroute('**/api/web/workspace');
// A second tab cannot silently overwrite a later save.
const p2=await browser.newPage({viewport:{width:1440,height:900}});await p2.goto(base+'/?view=home');await p2.locator('#capture-input').fill('另一标签较新的草稿 C');await p2.locator('.web-status[data-state=saved]').waitFor();await p.locator('#capture-input').fill('旧标签想覆盖的草稿 D');await p.locator('.web-status[data-state=error]').waitFor();check('stale tab CAS preserves newer data',(await state()).host.chain.capture.text==='另一标签较新的草稿 C');await shot('08-conflict');await p2.close();
check('no page errors',errors.length===0);
console.log('DONE '+out);
}catch(e){console.error(e.stack);if(p){await p.screenshot({path:path.join(out,'failure.png')});fs.writeFileSync(path.join(out,'failure-dom.txt'),await p.locator('body').innerText());}checks.push({name:'run error',passed:false,error:e.stack});process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,serverLog},null,2));await browser?.close();server.kill();console.log('EVIDENCE '+out);}})();
